///////////////////////////////////
//// This is a generated file. ////
////     Do not modify it.     ////
////       Generated by        ////
///////MessageGenerate.Gen.////////
///////////////////////////////////


using System.Collections.Generic;
using LGameFramework.GameNet;

namespace LGameFramework.GameLogic
{
    public class ModuleCfg
    {
        public BattlefieldConfig Battlefield { get; set; }
        public CommonConfig Common { get; set; }
        public GameRoomConfig GameRoom { get; set; }
        public LoginConfig Login { get; set; }
        public MainUIConfig MainUI { get; set; }
        public RoleConfig Role { get; set; }
    }

    public class ModuleData
    {
        public BattlefieldData Battlefield { get; set; }
        public CommonData Common { get; set; }
        public GameRoomData GameRoom { get; set; }
        public LoginData Login { get; set; }
        public MainUIData MainUI { get; set; }
        public RoleData Role { get; set; }
    }

    public class ModuleProxy
    {
        public BattlefieldProxy Battlefield { get; set; }
        public CommonProxy Common { get; set; }
        public GameRoomProxy GameRoom { get; set; }
        public LoginProxy Login { get; set; }
        public MainUIProxy MainUI { get; set; }
        public RoleProxy Role { get; set; }
    }
}
