///////////////////////////////////
//// This is a generated file. ////
////     Do not modify it.     ////
////       Generated by        ////
///////MessageGenerate.Gen.////////
///////////////////////////////////


using System;
using Google.Protobuf;

namespace GameServer
{
    public static class MQGenerate
    {
        public static object GetDeserialize(GameMessage.ENetworkCommand command, byte[] bytes)
        {
            switch (command)
            {
                case GameMessage.ENetworkCommand.SynClientFristFrame:
					return GameMessage.CommonStruct.Parser.ParseFrom(bytes);
				case GameMessage.ENetworkCommand.BattlefieldStartInfo:
					return GameMessage.BattlefieldStart.Parser.ParseFrom(bytes);
				case GameMessage.ENetworkCommand.SynClientOperation:
					return GameMessage.SyncFrameInfo.Parser.ParseFrom(bytes);
				case GameMessage.ENetworkCommand.GameRoomUpdateInfo:
					return GameMessage.GameRoomUpdateInfo.Parser.ParseFrom(bytes);
				default:
					return null;
            }
        }

        public static GameMessage.ENetworkCommand GetCommand(IMessage message)
        {
            switch (message)
            {
                case GameMessage.CommonStruct:
					return GameMessage.ENetworkCommand.SynClientFristFrame;
				case GameMessage.BattlefieldStart:
					return GameMessage.ENetworkCommand.BattlefieldStartInfo;
				case GameMessage.SyncFrameInfo:
					return GameMessage.ENetworkCommand.SynClientOperation;
				case GameMessage.GameRoomUpdateInfo:
					return GameMessage.ENetworkCommand.GameRoomUpdateInfo;
				default:
					break;

            }
            return GameMessage.ENetworkCommand.None;
        }
    }
}
