// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FightMsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameMessage {

  /// <summary>Holder for reflection information generated from FightMsg.proto</summary>
  public static partial class FightMsgReflection {

    #region Descriptor
    /// <summary>File descriptor for FightMsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FightMsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5GaWdodE1zZy5wcm90bxILR2FtZU1lc3NhZ2UaD1BsYXllck1zZy5wcm90",
            "bxoPQ29tbW9uTXNnLnByb3RvIuICChBCYXR0bGVmaWVsZFN0YXJ0Eg8KB2Zp",
            "Z2h0SUQYASABKAUSQQoKYWxsUGxheWVycxgCIAMoCzItLkdhbWVNZXNzYWdl",
            "LkJhdHRsZWZpZWxkU3RhcnQuQWxsUGxheWVyc0VudHJ5EkUKDGFsbENoYXJh",
            "Y3RlchgDIAMoCzIvLkdhbWVNZXNzYWdlLkJhdHRsZWZpZWxkU3RhcnQuQWxs",
            "Q2hhcmFjdGVyRW50cnkSFgoOc3RhcnRUaW1lc3RhbXAYBCABKAMaSgoPQWxs",
            "UGxheWVyc0VudHJ5EgsKA2tleRgBIAEoBRImCgV2YWx1ZRgCIAEoCzIXLkdh",
            "bWVNZXNzYWdlLlBsYXllckRhdGE6AjgBGk8KEUFsbENoYXJhY3RlckVudHJ5",
            "EgsKA2tleRgBIAEoBRIpCgV2YWx1ZRgCIAEoCzIaLkdhbWVNZXNzYWdlLkNo",
            "YXJhY3RlckRhdGE6AjgBIoIBChZPcGVyYXRpb25Db21tYW5kUmVjb3JkEg0K",
            "BWZyYW1lGAEgASgFEi4KB29wZXJhdGUYAiABKA4yHS5HYW1lTWVzc2FnZS5F",
            "Q2xpZW50T3BlcmF0aW9uEikKBHR5cGUYAyABKA4yGy5HYW1lTWVzc2FnZS5F",
            "T3BlcmF0aW9uVHlwZSKtAQoNT3BlcmF0aW9uSW5mbxINCgVmcmFtZRgBIAEo",
            "BRIPCgdmaWdodElEGAIgASgFEhAKCGNsaWVudElEGAMgASgFEjsKDm9wZXJh",
            "dGVDb21tYW5kGAQgAygLMiMuR2FtZU1lc3NhZ2UuT3BlcmF0aW9uQ29tbWFu",
            "ZFJlY29yZBItCglkaXJlY3Rpb24YBSABKAsyGi5HYW1lTWVzc2FnZS5Db21t",
            "b25WZWN0b3IzImMKEEFsbE9wZXJhdGlvbkluZm8SDQoFZnJhbWUYASABKAUS",
            "DwoHZmlnaHRJRBgCIAEoBRIvCgtvcGVyYXRlSW5mbxgDIAMoCzIaLkdhbWVN",
            "ZXNzYWdlLk9wZXJhdGlvbkluZm8iUQoNU3luY0ZyYW1lSW5mbxIPCgdmaWdo",
            "dElEGAEgASgFEi8KCGZyYW1lT3B0GAIgAygLMh0uR2FtZU1lc3NhZ2UuQWxs",
            "T3BlcmF0aW9uSW5mbyrPAQoQRUNsaWVudE9wZXJhdGlvbhILCgdOb3RoaW5n",
            "EAASCwoHRm9yd2FyZBABEgwKCEJhY2t3YXJkEAISCAoETGVmdBADEgkKBVJp",
            "Z2h0EAQSDwoLTGVmdEZvcndhcmQQBRIQCgxSaWdodEZvcndhcmQQBhIQCgxM",
            "ZWZ0QmFja3dhcmQQBxIRCg1SaWdodEJhY2t3YXJkEAgSCgoGQXR0YWNrEAkS",
            "CQoFU2tpbGwQChILCgdEZWZlbnNlEAsSCQoFRG9kZ2UQDBIHCgNFbmQQDSos",
            "Cg5FT3BlcmF0aW9uVHlwZRIICgREb3duEAASBgoCVXAQARIICgRIb2xkEAJi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GameMessage.PlayerMsgReflection.Descriptor, global::GameMessage.CommonMsgReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameMessage.EClientOperation), typeof(global::GameMessage.EOperationType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessage.BattlefieldStart), global::GameMessage.BattlefieldStart.Parser, new[]{ "FightID", "AllPlayers", "AllCharacter", "StartTimestamp" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessage.OperationCommandRecord), global::GameMessage.OperationCommandRecord.Parser, new[]{ "Frame", "Operate", "Type" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessage.OperationInfo), global::GameMessage.OperationInfo.Parser, new[]{ "Frame", "FightID", "ClientID", "OperateCommand", "Direction" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessage.AllOperationInfo), global::GameMessage.AllOperationInfo.Parser, new[]{ "Frame", "FightID", "OperateInfo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessage.SyncFrameInfo), global::GameMessage.SyncFrameInfo.Parser, new[]{ "FightID", "FrameOpt" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///客户端操作
  /// </summary>
  public enum EClientOperation {
    /// <summary>
    /// 无操作
    /// </summary>
    [pbr::OriginalName("Nothing")] Nothing = 0,
    /// <summary>
    /// 向前
    /// </summary>
    [pbr::OriginalName("Forward")] Forward = 1,
    /// <summary>
    /// 向后
    /// </summary>
    [pbr::OriginalName("Backward")] Backward = 2,
    /// <summary>
    /// 向左
    /// </summary>
    [pbr::OriginalName("Left")] Left = 3,
    /// <summary>
    /// 向右
    /// </summary>
    [pbr::OriginalName("Right")] Right = 4,
    /// <summary>
    /// 左前
    /// </summary>
    [pbr::OriginalName("LeftForward")] LeftForward = 5,
    /// <summary>
    /// 右前
    /// </summary>
    [pbr::OriginalName("RightForward")] RightForward = 6,
    /// <summary>
    /// 左后
    /// </summary>
    [pbr::OriginalName("LeftBackward")] LeftBackward = 7,
    /// <summary>
    /// 右后
    /// </summary>
    [pbr::OriginalName("RightBackward")] RightBackward = 8,
    /// <summary>
    /// 技能攻击
    /// </summary>
    [pbr::OriginalName("Attack")] Attack = 9,
    /// <summary>
    /// 技能攻击
    /// </summary>
    [pbr::OriginalName("Skill")] Skill = 10,
    /// <summary>
    /// 防御
    /// </summary>
    [pbr::OriginalName("Defense")] Defense = 11,
    /// <summary>
    /// 闪避
    /// </summary>
    [pbr::OriginalName("Dodge")] Dodge = 12,
    /// <summary>
    /// 枚举结束标识
    /// </summary>
    [pbr::OriginalName("End")] End = 13,
  }

  /// <summary>
  ///输入类型
  /// </summary>
  public enum EOperationType {
    /// <summary>
    ///按下
    /// </summary>
    [pbr::OriginalName("Down")] Down = 0,
    /// <summary>
    ///松开
    /// </summary>
    [pbr::OriginalName("Up")] Up = 1,
    /// <summary>
    ///按住
    /// </summary>
    [pbr::OriginalName("Hold")] Hold = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  ///战局开始
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BattlefieldStart : pb::IMessage<BattlefieldStart>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BattlefieldStart> _parser = new pb::MessageParser<BattlefieldStart>(() => new BattlefieldStart());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BattlefieldStart> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessage.FightMsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattlefieldStart() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattlefieldStart(BattlefieldStart other) : this() {
      fightID_ = other.fightID_;
      allPlayers_ = other.allPlayers_.Clone();
      allCharacter_ = other.allCharacter_.Clone();
      startTimestamp_ = other.startTimestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattlefieldStart Clone() {
      return new BattlefieldStart(this);
    }

    /// <summary>Field number for the "fightID" field.</summary>
    public const int FightIDFieldNumber = 1;
    private int fightID_;
    /// <summary>
    ///战局id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FightID {
      get { return fightID_; }
      set {
        fightID_ = value;
      }
    }

    /// <summary>Field number for the "allPlayers" field.</summary>
    public const int AllPlayersFieldNumber = 2;
    private static readonly pbc::MapField<int, global::GameMessage.PlayerData>.Codec _map_allPlayers_codec
        = new pbc::MapField<int, global::GameMessage.PlayerData>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::GameMessage.PlayerData.Parser), 18);
    private readonly pbc::MapField<int, global::GameMessage.PlayerData> allPlayers_ = new pbc::MapField<int, global::GameMessage.PlayerData>();
    /// <summary>
    ///参与的玩家
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::GameMessage.PlayerData> AllPlayers {
      get { return allPlayers_; }
    }

    /// <summary>Field number for the "allCharacter" field.</summary>
    public const int AllCharacterFieldNumber = 3;
    private static readonly pbc::MapField<int, global::GameMessage.CharacterData>.Codec _map_allCharacter_codec
        = new pbc::MapField<int, global::GameMessage.CharacterData>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::GameMessage.CharacterData.Parser), 26);
    private readonly pbc::MapField<int, global::GameMessage.CharacterData> allCharacter_ = new pbc::MapField<int, global::GameMessage.CharacterData>();
    /// <summary>
    ///创建的角色
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::GameMessage.CharacterData> AllCharacter {
      get { return allCharacter_; }
    }

    /// <summary>Field number for the "startTimestamp" field.</summary>
    public const int StartTimestampFieldNumber = 4;
    private long startTimestamp_;
    /// <summary>
    ///开始时间戳
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long StartTimestamp {
      get { return startTimestamp_; }
      set {
        startTimestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BattlefieldStart);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BattlefieldStart other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FightID != other.FightID) return false;
      if (!AllPlayers.Equals(other.AllPlayers)) return false;
      if (!AllCharacter.Equals(other.AllCharacter)) return false;
      if (StartTimestamp != other.StartTimestamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FightID != 0) hash ^= FightID.GetHashCode();
      hash ^= AllPlayers.GetHashCode();
      hash ^= AllCharacter.GetHashCode();
      if (StartTimestamp != 0L) hash ^= StartTimestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FightID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(FightID);
      }
      allPlayers_.WriteTo(output, _map_allPlayers_codec);
      allCharacter_.WriteTo(output, _map_allCharacter_codec);
      if (StartTimestamp != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(StartTimestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FightID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(FightID);
      }
      allPlayers_.WriteTo(ref output, _map_allPlayers_codec);
      allCharacter_.WriteTo(ref output, _map_allCharacter_codec);
      if (StartTimestamp != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(StartTimestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FightID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FightID);
      }
      size += allPlayers_.CalculateSize(_map_allPlayers_codec);
      size += allCharacter_.CalculateSize(_map_allCharacter_codec);
      if (StartTimestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartTimestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BattlefieldStart other) {
      if (other == null) {
        return;
      }
      if (other.FightID != 0) {
        FightID = other.FightID;
      }
      allPlayers_.MergeFrom(other.allPlayers_);
      allCharacter_.MergeFrom(other.allCharacter_);
      if (other.StartTimestamp != 0L) {
        StartTimestamp = other.StartTimestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FightID = input.ReadInt32();
            break;
          }
          case 18: {
            allPlayers_.AddEntriesFrom(input, _map_allPlayers_codec);
            break;
          }
          case 26: {
            allCharacter_.AddEntriesFrom(input, _map_allCharacter_codec);
            break;
          }
          case 32: {
            StartTimestamp = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FightID = input.ReadInt32();
            break;
          }
          case 18: {
            allPlayers_.AddEntriesFrom(ref input, _map_allPlayers_codec);
            break;
          }
          case 26: {
            allCharacter_.AddEntriesFrom(ref input, _map_allCharacter_codec);
            break;
          }
          case 32: {
            StartTimestamp = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///操作命令记录
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OperationCommandRecord : pb::IMessage<OperationCommandRecord>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OperationCommandRecord> _parser = new pb::MessageParser<OperationCommandRecord>(() => new OperationCommandRecord());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OperationCommandRecord> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessage.FightMsgReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OperationCommandRecord() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OperationCommandRecord(OperationCommandRecord other) : this() {
      frame_ = other.frame_;
      operate_ = other.operate_;
      type_ = other.type_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OperationCommandRecord Clone() {
      return new OperationCommandRecord(this);
    }

    /// <summary>Field number for the "frame" field.</summary>
    public const int FrameFieldNumber = 1;
    private int frame_;
    /// <summary>
    ///第几帧输入的
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Frame {
      get { return frame_; }
      set {
        frame_ = value;
      }
    }

    /// <summary>Field number for the "operate" field.</summary>
    public const int OperateFieldNumber = 2;
    private global::GameMessage.EClientOperation operate_ = global::GameMessage.EClientOperation.Nothing;
    /// <summary>
    ///输入的操作
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameMessage.EClientOperation Operate {
      get { return operate_; }
      set {
        operate_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 3;
    private global::GameMessage.EOperationType type_ = global::GameMessage.EOperationType.Down;
    /// <summary>
    ///操作类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameMessage.EOperationType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OperationCommandRecord);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OperationCommandRecord other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Frame != other.Frame) return false;
      if (Operate != other.Operate) return false;
      if (Type != other.Type) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Frame != 0) hash ^= Frame.GetHashCode();
      if (Operate != global::GameMessage.EClientOperation.Nothing) hash ^= Operate.GetHashCode();
      if (Type != global::GameMessage.EOperationType.Down) hash ^= Type.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Frame != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Frame);
      }
      if (Operate != global::GameMessage.EClientOperation.Nothing) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Operate);
      }
      if (Type != global::GameMessage.EOperationType.Down) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Frame != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Frame);
      }
      if (Operate != global::GameMessage.EClientOperation.Nothing) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Operate);
      }
      if (Type != global::GameMessage.EOperationType.Down) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Frame != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Frame);
      }
      if (Operate != global::GameMessage.EClientOperation.Nothing) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Operate);
      }
      if (Type != global::GameMessage.EOperationType.Down) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OperationCommandRecord other) {
      if (other == null) {
        return;
      }
      if (other.Frame != 0) {
        Frame = other.Frame;
      }
      if (other.Operate != global::GameMessage.EClientOperation.Nothing) {
        Operate = other.Operate;
      }
      if (other.Type != global::GameMessage.EOperationType.Down) {
        Type = other.Type;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Frame = input.ReadInt32();
            break;
          }
          case 16: {
            Operate = (global::GameMessage.EClientOperation) input.ReadEnum();
            break;
          }
          case 24: {
            Type = (global::GameMessage.EOperationType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Frame = input.ReadInt32();
            break;
          }
          case 16: {
            Operate = (global::GameMessage.EClientOperation) input.ReadEnum();
            break;
          }
          case 24: {
            Type = (global::GameMessage.EOperationType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///操作信息
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OperationInfo : pb::IMessage<OperationInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OperationInfo> _parser = new pb::MessageParser<OperationInfo>(() => new OperationInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OperationInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessage.FightMsgReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OperationInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OperationInfo(OperationInfo other) : this() {
      frame_ = other.frame_;
      fightID_ = other.fightID_;
      clientID_ = other.clientID_;
      operateCommand_ = other.operateCommand_.Clone();
      direction_ = other.direction_ != null ? other.direction_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OperationInfo Clone() {
      return new OperationInfo(this);
    }

    /// <summary>Field number for the "frame" field.</summary>
    public const int FrameFieldNumber = 1;
    private int frame_;
    /// <summary>
    ///哪一帧
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Frame {
      get { return frame_; }
      set {
        frame_ = value;
      }
    }

    /// <summary>Field number for the "fightID" field.</summary>
    public const int FightIDFieldNumber = 2;
    private int fightID_;
    /// <summary>
    ///战局id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FightID {
      get { return fightID_; }
      set {
        fightID_ = value;
      }
    }

    /// <summary>Field number for the "clientID" field.</summary>
    public const int ClientIDFieldNumber = 3;
    private int clientID_;
    /// <summary>
    ///客户端在服务端的id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ClientID {
      get { return clientID_; }
      set {
        clientID_ = value;
      }
    }

    /// <summary>Field number for the "operateCommand" field.</summary>
    public const int OperateCommandFieldNumber = 4;
    private static readonly pb::FieldCodec<global::GameMessage.OperationCommandRecord> _repeated_operateCommand_codec
        = pb::FieldCodec.ForMessage(34, global::GameMessage.OperationCommandRecord.Parser);
    private readonly pbc::RepeatedField<global::GameMessage.OperationCommandRecord> operateCommand_ = new pbc::RepeatedField<global::GameMessage.OperationCommandRecord>();
    /// <summary>
    ///这一帧的所有操作
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::GameMessage.OperationCommandRecord> OperateCommand {
      get { return operateCommand_; }
    }

    /// <summary>Field number for the "direction" field.</summary>
    public const int DirectionFieldNumber = 5;
    private global::GameMessage.CommonVector3 direction_;
    /// <summary>
    ///移动方向
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameMessage.CommonVector3 Direction {
      get { return direction_; }
      set {
        direction_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OperationInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OperationInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Frame != other.Frame) return false;
      if (FightID != other.FightID) return false;
      if (ClientID != other.ClientID) return false;
      if(!operateCommand_.Equals(other.operateCommand_)) return false;
      if (!object.Equals(Direction, other.Direction)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Frame != 0) hash ^= Frame.GetHashCode();
      if (FightID != 0) hash ^= FightID.GetHashCode();
      if (ClientID != 0) hash ^= ClientID.GetHashCode();
      hash ^= operateCommand_.GetHashCode();
      if (direction_ != null) hash ^= Direction.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Frame != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Frame);
      }
      if (FightID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FightID);
      }
      if (ClientID != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ClientID);
      }
      operateCommand_.WriteTo(output, _repeated_operateCommand_codec);
      if (direction_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Direction);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Frame != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Frame);
      }
      if (FightID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FightID);
      }
      if (ClientID != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ClientID);
      }
      operateCommand_.WriteTo(ref output, _repeated_operateCommand_codec);
      if (direction_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Direction);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Frame != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Frame);
      }
      if (FightID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FightID);
      }
      if (ClientID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClientID);
      }
      size += operateCommand_.CalculateSize(_repeated_operateCommand_codec);
      if (direction_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Direction);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OperationInfo other) {
      if (other == null) {
        return;
      }
      if (other.Frame != 0) {
        Frame = other.Frame;
      }
      if (other.FightID != 0) {
        FightID = other.FightID;
      }
      if (other.ClientID != 0) {
        ClientID = other.ClientID;
      }
      operateCommand_.Add(other.operateCommand_);
      if (other.direction_ != null) {
        if (direction_ == null) {
          Direction = new global::GameMessage.CommonVector3();
        }
        Direction.MergeFrom(other.Direction);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Frame = input.ReadInt32();
            break;
          }
          case 16: {
            FightID = input.ReadInt32();
            break;
          }
          case 24: {
            ClientID = input.ReadInt32();
            break;
          }
          case 34: {
            operateCommand_.AddEntriesFrom(input, _repeated_operateCommand_codec);
            break;
          }
          case 42: {
            if (direction_ == null) {
              Direction = new global::GameMessage.CommonVector3();
            }
            input.ReadMessage(Direction);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Frame = input.ReadInt32();
            break;
          }
          case 16: {
            FightID = input.ReadInt32();
            break;
          }
          case 24: {
            ClientID = input.ReadInt32();
            break;
          }
          case 34: {
            operateCommand_.AddEntriesFrom(ref input, _repeated_operateCommand_codec);
            break;
          }
          case 42: {
            if (direction_ == null) {
              Direction = new global::GameMessage.CommonVector3();
            }
            input.ReadMessage(Direction);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///这一句所有玩家的操作信息
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AllOperationInfo : pb::IMessage<AllOperationInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AllOperationInfo> _parser = new pb::MessageParser<AllOperationInfo>(() => new AllOperationInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AllOperationInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessage.FightMsgReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AllOperationInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AllOperationInfo(AllOperationInfo other) : this() {
      frame_ = other.frame_;
      fightID_ = other.fightID_;
      operateInfo_ = other.operateInfo_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AllOperationInfo Clone() {
      return new AllOperationInfo(this);
    }

    /// <summary>Field number for the "frame" field.</summary>
    public const int FrameFieldNumber = 1;
    private int frame_;
    /// <summary>
    ///哪一帧
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Frame {
      get { return frame_; }
      set {
        frame_ = value;
      }
    }

    /// <summary>Field number for the "fightID" field.</summary>
    public const int FightIDFieldNumber = 2;
    private int fightID_;
    /// <summary>
    ///战场id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FightID {
      get { return fightID_; }
      set {
        fightID_ = value;
      }
    }

    /// <summary>Field number for the "operateInfo" field.</summary>
    public const int OperateInfoFieldNumber = 3;
    private static readonly pb::FieldCodec<global::GameMessage.OperationInfo> _repeated_operateInfo_codec
        = pb::FieldCodec.ForMessage(26, global::GameMessage.OperationInfo.Parser);
    private readonly pbc::RepeatedField<global::GameMessage.OperationInfo> operateInfo_ = new pbc::RepeatedField<global::GameMessage.OperationInfo>();
    /// <summary>
    ///所有玩家操作
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::GameMessage.OperationInfo> OperateInfo {
      get { return operateInfo_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AllOperationInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AllOperationInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Frame != other.Frame) return false;
      if (FightID != other.FightID) return false;
      if(!operateInfo_.Equals(other.operateInfo_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Frame != 0) hash ^= Frame.GetHashCode();
      if (FightID != 0) hash ^= FightID.GetHashCode();
      hash ^= operateInfo_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Frame != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Frame);
      }
      if (FightID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FightID);
      }
      operateInfo_.WriteTo(output, _repeated_operateInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Frame != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Frame);
      }
      if (FightID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FightID);
      }
      operateInfo_.WriteTo(ref output, _repeated_operateInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Frame != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Frame);
      }
      if (FightID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FightID);
      }
      size += operateInfo_.CalculateSize(_repeated_operateInfo_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AllOperationInfo other) {
      if (other == null) {
        return;
      }
      if (other.Frame != 0) {
        Frame = other.Frame;
      }
      if (other.FightID != 0) {
        FightID = other.FightID;
      }
      operateInfo_.Add(other.operateInfo_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Frame = input.ReadInt32();
            break;
          }
          case 16: {
            FightID = input.ReadInt32();
            break;
          }
          case 26: {
            operateInfo_.AddEntriesFrom(input, _repeated_operateInfo_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Frame = input.ReadInt32();
            break;
          }
          case 16: {
            FightID = input.ReadInt32();
            break;
          }
          case 26: {
            operateInfo_.AddEntriesFrom(ref input, _repeated_operateInfo_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///同步帧信息
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SyncFrameInfo : pb::IMessage<SyncFrameInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SyncFrameInfo> _parser = new pb::MessageParser<SyncFrameInfo>(() => new SyncFrameInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SyncFrameInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessage.FightMsgReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SyncFrameInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SyncFrameInfo(SyncFrameInfo other) : this() {
      fightID_ = other.fightID_;
      frameOpt_ = other.frameOpt_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SyncFrameInfo Clone() {
      return new SyncFrameInfo(this);
    }

    /// <summary>Field number for the "fightID" field.</summary>
    public const int FightIDFieldNumber = 1;
    private int fightID_;
    /// <summary>
    ///战场id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FightID {
      get { return fightID_; }
      set {
        fightID_ = value;
      }
    }

    /// <summary>Field number for the "frameOpt" field.</summary>
    public const int FrameOptFieldNumber = 2;
    private static readonly pb::FieldCodec<global::GameMessage.AllOperationInfo> _repeated_frameOpt_codec
        = pb::FieldCodec.ForMessage(18, global::GameMessage.AllOperationInfo.Parser);
    private readonly pbc::RepeatedField<global::GameMessage.AllOperationInfo> frameOpt_ = new pbc::RepeatedField<global::GameMessage.AllOperationInfo>();
    /// <summary>
    ///发送的帧信息（有可能补发）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::GameMessage.AllOperationInfo> FrameOpt {
      get { return frameOpt_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SyncFrameInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SyncFrameInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FightID != other.FightID) return false;
      if(!frameOpt_.Equals(other.frameOpt_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FightID != 0) hash ^= FightID.GetHashCode();
      hash ^= frameOpt_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FightID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(FightID);
      }
      frameOpt_.WriteTo(output, _repeated_frameOpt_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FightID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(FightID);
      }
      frameOpt_.WriteTo(ref output, _repeated_frameOpt_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FightID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FightID);
      }
      size += frameOpt_.CalculateSize(_repeated_frameOpt_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SyncFrameInfo other) {
      if (other == null) {
        return;
      }
      if (other.FightID != 0) {
        FightID = other.FightID;
      }
      frameOpt_.Add(other.frameOpt_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FightID = input.ReadInt32();
            break;
          }
          case 18: {
            frameOpt_.AddEntriesFrom(input, _repeated_frameOpt_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FightID = input.ReadInt32();
            break;
          }
          case 18: {
            frameOpt_.AddEntriesFrom(ref input, _repeated_frameOpt_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
