// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameRoomMsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameMessage {

  /// <summary>Holder for reflection information generated from GameRoomMsg.proto</summary>
  public static partial class GameRoomMsgReflection {

    #region Descriptor
    /// <summary>File descriptor for GameRoomMsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameRoomMsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFHYW1lUm9vbU1zZy5wcm90bxILR2FtZU1lc3NhZ2UaD1BsYXllck1zZy5w",
            "cm90byKIAQoSR2FtZVJvb21VcGRhdGVJbmZvEg4KBnJvb21JZBgBIAEoBRIQ",
            "Cghyb29tTmFtZRgCIAEoCRIQCghtYXN0ZXJJZBgDIAEoBRIsCgtqb2luUGxh",
            "eWVycxgEIAMoCzIXLkdhbWVNZXNzYWdlLlBsYXllckRhdGESEAoIaXNSZWFk",
            "eXMYBSADKAUiWwoPR2FtZVJvb21BbGxJbmZvEhEKCXJvb21Db3VudBgBIAEo",
            "BRIOCgZyb29tSWQYAiADKAUSEAoIcm9vbU5hbWUYAyADKAkSEwoLcGxheWVy",
            "Q291bnQYBCADKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GameMessage.PlayerMsgReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessage.GameRoomUpdateInfo), global::GameMessage.GameRoomUpdateInfo.Parser, new[]{ "RoomId", "RoomName", "MasterId", "JoinPlayers", "IsReadys" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessage.GameRoomAllInfo), global::GameMessage.GameRoomAllInfo.Parser, new[]{ "RoomCount", "RoomId", "RoomName", "PlayerCount" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///自己房间信息更新
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameRoomUpdateInfo : pb::IMessage<GameRoomUpdateInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameRoomUpdateInfo> _parser = new pb::MessageParser<GameRoomUpdateInfo>(() => new GameRoomUpdateInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameRoomUpdateInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessage.GameRoomMsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameRoomUpdateInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameRoomUpdateInfo(GameRoomUpdateInfo other) : this() {
      roomId_ = other.roomId_;
      roomName_ = other.roomName_;
      masterId_ = other.masterId_;
      joinPlayers_ = other.joinPlayers_.Clone();
      isReadys_ = other.isReadys_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameRoomUpdateInfo Clone() {
      return new GameRoomUpdateInfo(this);
    }

    /// <summary>Field number for the "roomId" field.</summary>
    public const int RoomIdFieldNumber = 1;
    private int roomId_;
    /// <summary>
    ///房间id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoomId {
      get { return roomId_; }
      set {
        roomId_ = value;
      }
    }

    /// <summary>Field number for the "roomName" field.</summary>
    public const int RoomNameFieldNumber = 2;
    private string roomName_ = "";
    /// <summary>
    ///房间名字
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RoomName {
      get { return roomName_; }
      set {
        roomName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "masterId" field.</summary>
    public const int MasterIdFieldNumber = 3;
    private int masterId_;
    /// <summary>
    ///房主id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MasterId {
      get { return masterId_; }
      set {
        masterId_ = value;
      }
    }

    /// <summary>Field number for the "joinPlayers" field.</summary>
    public const int JoinPlayersFieldNumber = 4;
    private static readonly pb::FieldCodec<global::GameMessage.PlayerData> _repeated_joinPlayers_codec
        = pb::FieldCodec.ForMessage(34, global::GameMessage.PlayerData.Parser);
    private readonly pbc::RepeatedField<global::GameMessage.PlayerData> joinPlayers_ = new pbc::RepeatedField<global::GameMessage.PlayerData>();
    /// <summary>
    ///参与的玩家
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::GameMessage.PlayerData> JoinPlayers {
      get { return joinPlayers_; }
    }

    /// <summary>Field number for the "isReadys" field.</summary>
    public const int IsReadysFieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_isReadys_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> isReadys_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///准备情况
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> IsReadys {
      get { return isReadys_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameRoomUpdateInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameRoomUpdateInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomId != other.RoomId) return false;
      if (RoomName != other.RoomName) return false;
      if (MasterId != other.MasterId) return false;
      if(!joinPlayers_.Equals(other.joinPlayers_)) return false;
      if(!isReadys_.Equals(other.isReadys_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RoomId != 0) hash ^= RoomId.GetHashCode();
      if (RoomName.Length != 0) hash ^= RoomName.GetHashCode();
      if (MasterId != 0) hash ^= MasterId.GetHashCode();
      hash ^= joinPlayers_.GetHashCode();
      hash ^= isReadys_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RoomId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoomId);
      }
      if (RoomName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RoomName);
      }
      if (MasterId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MasterId);
      }
      joinPlayers_.WriteTo(output, _repeated_joinPlayers_codec);
      isReadys_.WriteTo(output, _repeated_isReadys_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RoomId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoomId);
      }
      if (RoomName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RoomName);
      }
      if (MasterId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MasterId);
      }
      joinPlayers_.WriteTo(ref output, _repeated_joinPlayers_codec);
      isReadys_.WriteTo(ref output, _repeated_isReadys_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RoomId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomId);
      }
      if (RoomName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomName);
      }
      if (MasterId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MasterId);
      }
      size += joinPlayers_.CalculateSize(_repeated_joinPlayers_codec);
      size += isReadys_.CalculateSize(_repeated_isReadys_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameRoomUpdateInfo other) {
      if (other == null) {
        return;
      }
      if (other.RoomId != 0) {
        RoomId = other.RoomId;
      }
      if (other.RoomName.Length != 0) {
        RoomName = other.RoomName;
      }
      if (other.MasterId != 0) {
        MasterId = other.MasterId;
      }
      joinPlayers_.Add(other.joinPlayers_);
      isReadys_.Add(other.isReadys_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RoomId = input.ReadInt32();
            break;
          }
          case 18: {
            RoomName = input.ReadString();
            break;
          }
          case 24: {
            MasterId = input.ReadInt32();
            break;
          }
          case 34: {
            joinPlayers_.AddEntriesFrom(input, _repeated_joinPlayers_codec);
            break;
          }
          case 42:
          case 40: {
            isReadys_.AddEntriesFrom(input, _repeated_isReadys_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RoomId = input.ReadInt32();
            break;
          }
          case 18: {
            RoomName = input.ReadString();
            break;
          }
          case 24: {
            MasterId = input.ReadInt32();
            break;
          }
          case 34: {
            joinPlayers_.AddEntriesFrom(ref input, _repeated_joinPlayers_codec);
            break;
          }
          case 42:
          case 40: {
            isReadys_.AddEntriesFrom(ref input, _repeated_isReadys_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///所有房间的信息
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameRoomAllInfo : pb::IMessage<GameRoomAllInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameRoomAllInfo> _parser = new pb::MessageParser<GameRoomAllInfo>(() => new GameRoomAllInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameRoomAllInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessage.GameRoomMsgReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameRoomAllInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameRoomAllInfo(GameRoomAllInfo other) : this() {
      roomCount_ = other.roomCount_;
      roomId_ = other.roomId_.Clone();
      roomName_ = other.roomName_.Clone();
      playerCount_ = other.playerCount_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameRoomAllInfo Clone() {
      return new GameRoomAllInfo(this);
    }

    /// <summary>Field number for the "roomCount" field.</summary>
    public const int RoomCountFieldNumber = 1;
    private int roomCount_;
    /// <summary>
    ///总共的房间数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoomCount {
      get { return roomCount_; }
      set {
        roomCount_ = value;
      }
    }

    /// <summary>Field number for the "roomId" field.</summary>
    public const int RoomIdFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_roomId_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> roomId_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///所有的房间id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> RoomId {
      get { return roomId_; }
    }

    /// <summary>Field number for the "roomName" field.</summary>
    public const int RoomNameFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_roomName_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> roomName_ = new pbc::RepeatedField<string>();
    /// <summary>
    ///所有的房间名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> RoomName {
      get { return roomName_; }
    }

    /// <summary>Field number for the "playerCount" field.</summary>
    public const int PlayerCountFieldNumber = 4;
    private static readonly pb::FieldCodec<int> _repeated_playerCount_codec
        = pb::FieldCodec.ForInt32(34);
    private readonly pbc::RepeatedField<int> playerCount_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///房间人数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> PlayerCount {
      get { return playerCount_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameRoomAllInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameRoomAllInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomCount != other.RoomCount) return false;
      if(!roomId_.Equals(other.roomId_)) return false;
      if(!roomName_.Equals(other.roomName_)) return false;
      if(!playerCount_.Equals(other.playerCount_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RoomCount != 0) hash ^= RoomCount.GetHashCode();
      hash ^= roomId_.GetHashCode();
      hash ^= roomName_.GetHashCode();
      hash ^= playerCount_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RoomCount != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoomCount);
      }
      roomId_.WriteTo(output, _repeated_roomId_codec);
      roomName_.WriteTo(output, _repeated_roomName_codec);
      playerCount_.WriteTo(output, _repeated_playerCount_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RoomCount != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoomCount);
      }
      roomId_.WriteTo(ref output, _repeated_roomId_codec);
      roomName_.WriteTo(ref output, _repeated_roomName_codec);
      playerCount_.WriteTo(ref output, _repeated_playerCount_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RoomCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomCount);
      }
      size += roomId_.CalculateSize(_repeated_roomId_codec);
      size += roomName_.CalculateSize(_repeated_roomName_codec);
      size += playerCount_.CalculateSize(_repeated_playerCount_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameRoomAllInfo other) {
      if (other == null) {
        return;
      }
      if (other.RoomCount != 0) {
        RoomCount = other.RoomCount;
      }
      roomId_.Add(other.roomId_);
      roomName_.Add(other.roomName_);
      playerCount_.Add(other.playerCount_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RoomCount = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            roomId_.AddEntriesFrom(input, _repeated_roomId_codec);
            break;
          }
          case 26: {
            roomName_.AddEntriesFrom(input, _repeated_roomName_codec);
            break;
          }
          case 34:
          case 32: {
            playerCount_.AddEntriesFrom(input, _repeated_playerCount_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RoomCount = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            roomId_.AddEntriesFrom(ref input, _repeated_roomId_codec);
            break;
          }
          case 26: {
            roomName_.AddEntriesFrom(ref input, _repeated_roomName_codec);
            break;
          }
          case 34:
          case 32: {
            playerCount_.AddEntriesFrom(ref input, _repeated_playerCount_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
