///////////////////////////////////
//// This is a generated file. ////
////     Do not modify it.     ////
////       Generated by        ////
///////MessageGenerate.Gen.////////
///////////////////////////////////


using System;
using GameMessage;
using Google.Protobuf;
using LGameFramework.GameNet;

namespace GameNet
{
    public static class ILogin
    {

        #region Login Interface Begin
        private static ByteBuffer LoginInternal(int uid)
        {
            var msgIdArr = MessageSender.SendID.ToByteArray();
            var msgIdLen = msgIdArr.Length;
            var identityArr = "ILogin.Login".ToByteArray();
            var identityLen = identityArr.Length;
            var uidArr = uid.ToByteArray();
			var uidLen = uidArr.Length;;
			
            int bodyLen = identityLen + uidLen;
            var bodyLenArr = bodyLen.ToByteArray();
            int len = msgIdLen + 4 + bodyLen;
            ByteBuffer buffer = new ByteBuffer(len);
            buffer.Write(msgIdArr);
			buffer.Write(bodyLenArr);
			buffer.Write(identityArr);
			buffer.Write(uidArr);
			

            return buffer;
        }

        public static void Login(int uid, Action<int> response)
        {
            void ILogin_Login_response(byte[] bytes)
            {
                ByteBuffer buffer = new ByteBuffer(bytes);
                var clientId = buffer.ReadInt();
				
                response.Invoke(clientId);
            }

            ByteBuffer buffer = LoginInternal(uid);
            NetworkUtility.Send(buffer, ILogin_Login_response);
        }

        public static void LoginAsyn(int uid, Action<int> response)
        {
            void ILogin_Login_response(byte[] bytes)
            {
                ByteBuffer buffer = new ByteBuffer(bytes);
                var clientId = buffer.ReadInt();
				
                response.Invoke(clientId);
            }

            ByteBuffer buffer = LoginInternal(uid);
            NetworkUtility.SendAsyn(buffer, ILogin_Login_response);
        }
        #endregion Login Interface End

        #region Logout Interface Begin
        private static ByteBuffer LogoutInternal(int uid)
        {
            var msgIdArr = MessageSender.SendID.ToByteArray();
            var msgIdLen = msgIdArr.Length;
            var identityArr = "ILogin.Logout".ToByteArray();
            var identityLen = identityArr.Length;
            var uidArr = uid.ToByteArray();
			var uidLen = uidArr.Length;;
			
            int bodyLen = identityLen + uidLen;
            var bodyLenArr = bodyLen.ToByteArray();
            int len = msgIdLen + 4 + bodyLen;
            ByteBuffer buffer = new ByteBuffer(len);
            buffer.Write(msgIdArr);
			buffer.Write(bodyLenArr);
			buffer.Write(identityArr);
			buffer.Write(uidArr);
			

            return buffer;
        }

        public static void Logout(int uid, Action response)
        {
            void ILogin_Logout_response(byte[] bytes)
            {

                response.Invoke();
            }

            ByteBuffer buffer = LogoutInternal(uid);
            NetworkUtility.Send(buffer, ILogin_Logout_response);
        }

        public static void LogoutAsyn(int uid, Action response)
        {
            void ILogin_Logout_response(byte[] bytes)
            {

                response.Invoke();
            }

            ByteBuffer buffer = LogoutInternal(uid);
            NetworkUtility.SendAsyn(buffer, ILogin_Logout_response);
        }
        #endregion Logout Interface End
    }
}
